- name: Клонирование репозитория frontend
  git:
    repo: "https://github.com/d1zzy13/Frontend.git"
    dest: "/mnt/с/ansible_project/frontend"
  become: true
  tags: clone_repository

- name: Клонирование репозитория backend
  git:
    repo: "https://github.com/d1zzy13/Backend.git"
    dest: "/mnt/c/ansible_project/backend"
  become: true
  tags: clone_repository

- name: Клонирование репозитория devops
  git:
    repo: "https://github.com/d1zzy13/DevOps.git"
    dest: "/mnt/c/ansible_project/devops"
  become: true
  tags: clone_repository

- name: Создание папки data
  file:
    path: /mnt/d/ansible_project/data
    state: directory
    mode: '0755'
  become: true
  tags: clone_repository

- name: Создание файла data.txt в папке data
  copy:
    content: ""
    dest: /mnt/d/ansible_project/data/data.txt
    mode: '0644'
  become: true
  tags: clone_repository